version: '3.8'
services:
    client:
        build: ./
        container_name: client_c
        env_file: .docker.env
        ports:
            - 3000:3000
        stdin_open: true
        tty: true
