version: "3.8"
services:
  server: 
    build: ./server
    container_name: server_c
    ports:
      - 3001:3001
    env_file: ./server/.docker.env
    volumes: 
      - ./server/storage:/var/lib/serverData/storage
    stdin_open: true
    tty: true
  client: 
    build: ./client
    container_name: client_c
    env_file: ./client/.docker.env
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    