version: '3.8'
services:
    server:
        build: ./
        container_name: server_c
        ports:
            - 3001:3001
        env_file: .docker.env
        volumes:
            - ./storage:/var/lib/serverData/storage
        stdin_open: true
        tty: true
