name: FileKeeper server

on:
  push:
    branches: 
    - dev
  pull_request:
    branches:
    - dev
    
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
        
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'npm'
          cache-dependency-path: 'server/package-lock.json'
      - name: Install Eslint
        run: |
          npm ci
      - name: Eslint working flow
        run: |
          npm run eslint
